version: '3'

services:
  db:
    image: mysql:5.7
    volumes: 
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  pma:
    depends_on: 
      - db
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_ARBITRATY: 1
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 123
    ports:
     - 6002:80

  app:
    depends_on: 
      - db
    image: bitnami/php-fpm:latest
    expose: 
      - "9000"
    restart: always
    volumes:
      - ./wordpress:/var/www/html

  lb:
    depends_on: 
      - app
    image: nginx:latest
    ports: 
      - "6001:80"
    restart: always
    volumes: 
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./wordpress:/var/www/html

volumes:
  db_data: {}
